[package]
name = "mercury"
version = "0.1.0"
authors = ["Daniel Olsen <daniel.olsen99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
coz = "0.1"

[profile.release]
debug = 1